package com.lorenzovainigli.foodexpirationdates.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF934B00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCC5)
val md_theme_light_onPrimaryContainer = Color(0xFF301400)
val md_theme_light_secondary = Color(0xFF755945)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCC5)
val md_theme_light_onSecondaryContainer = Color(0xFF2A1708)
val md_theme_light_tertiary = Color(0xFF5E6135)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE3E6AF)
val md_theme_light_onTertiaryContainer = Color(0xFF1B1D00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A17)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A17)
val md_theme_light_surfaceVariant = Color(0xFFF3DFD2)
val md_theme_light_onSurfaceVariant = Color(0xFF52443B)
val md_theme_light_outline = Color(0xFF84746A)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEE8)
val md_theme_light_inverseSurface = Color(0xFF362F2B)
val md_theme_light_inversePrimary = Color(0xFFFFB782)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF934B00)
val md_theme_light_outlineVariant = Color(0xFFD6C3B7)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB782)
val md_theme_dark_onPrimary = Color(0xFF4F2500)
val md_theme_dark_primaryContainer = Color(0xFF703800)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCC5)
val md_theme_dark_secondary = Color(0xFFE4BFA7)
val md_theme_dark_onSecondary = Color(0xFF422B1A)
val md_theme_dark_secondaryContainer = Color(0xFF5B412F)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC5)
val md_theme_dark_tertiary = Color(0xFFC7CA95)
val md_theme_dark_onTertiary = Color(0xFF30330B)
val md_theme_dark_tertiaryContainer = Color(0xFF464920)
val md_theme_dark_onTertiaryContainer = Color(0xFFE3E6AF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A17)
val md_theme_dark_onBackground = Color(0xFFECE0DA)
val md_theme_dark_surface = Color(0xFF201A17)
val md_theme_dark_onSurface = Color(0xFFECE0DA)
val md_theme_dark_surfaceVariant = Color(0xFF52443B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD6C3B7)
val md_theme_dark_outline = Color(0xFF9F8D83)
val md_theme_dark_inverseOnSurface = Color(0xFF201A17)
val md_theme_dark_inverseSurface = Color(0xFFECE0DA)
val md_theme_dark_inversePrimary = Color(0xFF934B00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB782)
val md_theme_dark_outlineVariant = Color(0xFF52443B)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFFEA7D10)

val Red700 = Color(0xFFD32F2F)
val Orange500 = Color(0xFFFF9800)
val Yellow500 = Color(0xFFFFEB3B)
